language: python

python: "2.7"

sudo: false

git:
  submodules: false

cache:
  pip: true
  apt: true
  directories:
    - output
    - pelican-plugins

addons:
  apt:
    packages:
    - gettext
    - libjpeg-turbo-progs
    - optipng
    - python-pip
    - python-virtualenv

script: make html

jobs:
  include:
      - stage: prepare cache
        script: git submodule init pelican-plugins ; git submodule update
