language: python

python: "2.7"

sudo: false

git:
  submodules: false

cache:
  pip: true
  apt: true
  directories:
    - output
    - pelican-plugins

addons:
  apt:
    packages:
    - gettext
    - libjpeg-turbo-progs
    - optipng
    - python-pip
    - python-virtualenv

script: make html

deploy:
  - provider: script
    script: aws s3 sync --region=us-east-1 output/ s3://website-staging.freenetproject.org
    skip_cleanup: true
    on:
      branch: 2016-redesign
  - provider: script
    script: aws s3 sync --region=us-east-1 output/ s3://website-freenetproject.org
    skip_cleanup: true
    on:
      tags: true

jobs:
  include:
      - stage: prepare cache
        script: git submodule init pelican-plugins ; git submodule update pelican-plugins
